[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "trade-account-registry"

[dependencies]
contract_schema = { path = "../schema" }
contract_libs = { path = "../libs" }
ownership = "0.26.1"
pausable = "0.26.2"
bytecode = "0.26.1"
src5 = "0.8.1"
src12 = "0.8.0"
src14 = "0.8.0"
