[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
# entry = "main.sw"
entry = "main.adjusted.sw"
license = "Apache-2.0"
name = "order-book"

[dependencies]
contract_schema = { path = "../schema" }
contract_libs = { path = "../libs" }
ownership = "0.26.1"
pausable = "0.26.2"
src5 = "0.8.1"
