[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "trade-account-oracle"

[dependencies]
contract_schema = { path = "../schema" }
ownership = "0.26.1"
pausable = "0.26.0"
src5 = "0.8.1"
