[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "order-book-blacklist"

[dependencies]
contract_schema = { path = "../schema" }
ownership = "0.26.1"
src5 = "0.8.0"
