[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "trade-account"

[dependencies]
contract_schema = { path = "../schema" }
contract_libs = { path = "../libs" }
upgradability = "0.26.0"
